uploads = []
generated = []

[[outputs]]
id = "RPXP3Ossx99R_fpQSS8q-"
uri = "file://sparro-fx-ai-src.zip"
type = "unspecified"
title = "Sparro FX AI — all source files"

[[outputs]]
id = "vZL9OUjkaBxNqDasCb-6C"
uri = "file://sparro-backend.zip"
type = "unspecified"
title = "Sparro FX AI — Railway Backend"
